#cloud-config

timezone: Asia/Tokyo
locale: ja_JP.utf8

disk_setup:
  /dev/nvme1n1:
    table_type: gpt
    layout: [20, 80] # 20% を /dev/nvme1n1p1 に、残りを /dev/nvme1n1p2 に割り当てる
    overwrite: false

fs_setup:
  # nix のパッケージ用
  - label: nix-data
    filesystem: xfs
    device: /dev/nvme1n1p1
    overwrite: false
  # Jenkins 用
  - label: jenkins
    filesystem: xfs
    device: /dev/nvme1n1p2
    overwrite: false

write_files:
  - path: /etc/sysctl.d/99-unprivileged-ports.conf
    content: |
      net.ipv4.ip_unprivileged_port_start = 80
    owner: root:root
    permissions: "0644"

runcmd:
  # ディスクまわりの処理待ち
  - udevadm settle
  # マウント先のディレクトリ（マウントポイント）を確実に作成
  - mkdir -p /nix
  - mkdir -p /mnt/jenkins
  # /etc/fstab へ LABEL 形式で追加
  - echo "LABEL=nix-data /nix xfs defaults,nofail 0 2" >> /etc/fstab
  - echo "LABEL=jenkins /mnt/jenkins xfs defaults,nofail 0 2" >> /etc/fstab
  # fstab の設定に従って即座にマウントを実行
  - mount -a
  # jenkins データディレクトリの所有者を ec2-user に変更
  - chown ec2-user:ec2-user /mnt/jenkins
  # sysctl の設定を反映
  - sysctl --system
  # ec2-user の linger を有効化（ログインしていない状態でもユーザーサービスを実行可能にする）
  - loginctl enable-linger "ec2-user"
