services:
  jenkins-al2023:
    image: amazonlinux:2023
    container_name: jenkins-al2023
    tty: true
    stdin_open: true
    volumes:
      - ./dotfiles:/workspace/dotfiles
    working_dir: /workspace/dotfiles
