#!/usr/bin/env bash

# shellcheck disable=SC2034
{
  RED='\033[0;31m'
  YELLOW='\033[1;33m'
  GREEN='\033[0;32m'
  CYAN='\033[0;36m'

  NC='\033[0m'
}

function log_step() {
  echo -e "${GREEN}[STEP ]${NC} $*"
}

function log_debug() {
  echo -e "${CYAN}[DEBUG]${NC} $*"
}

function log_info() {
  echo -e "${GREEN}[INFO ]${NC} $*"
}

function log_warning() {
  echo -e "${YELLOW}[WARN ]${NC} $*"
}

function log_error() {
  echo -e "${RED}[ERROR]${NC} $*"
}
